name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Set up JDK (Java 17 is recommended for modern Android builds)
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # 4. Accept all Android SDK licenses
      - name: Accept Android SDK Licenses
        run: yes | sdkmanager --licenses

      # 5. Install required build tools
      - name: Install SDK Build Tools
        run: |
          sdkmanager "platform-tools" \
                     "platforms;android-34" \
                     "build-tools;34.0.0" \
                     "cmdline-tools;latest"

      # 6. Create cmdline-tools directory (if needed)
      - name: Create cmdline-tools directory
        run: mkdir -p $ANDROID_HOME/cmdline-tools

      # 7. Make Gradlew executable
      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      # 8. Build Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # 9. Upload the generated APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
          run: |
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;34.0.0" "ndk;25.2.9519653"

      # 6. Make Gradlew executable
      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      # 7. Build the APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      # 8. Upload the APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
          run:  mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9123335_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d latest
          rm cmdline-tools.zip

          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      # 5. Install NDK
      - name: Install NDK
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          yes | sdkmanager --install "ndk;23.1.7779620"

      # 6. Accept all licenses
      - name: Accept Licenses
        run: yes | sdkmanager --licenses

      # 7. Check if Gradle Wrapper exists
      - name: Check for Gradle Wrapper
        id: check-wrapper
        run: |
          if [ -f "./gradlew" ]; then
            echo "wrapper=true" >> $GITHUB_ENV
          else
            echo "wrapper=false" >> $GITHUB_ENV
          fi

      # 8. Install Gradle if wrapper missing
      - name: Install Gradle
        if: env.wrapper == 'false'
        run: |
          sudo apt-get install -y gradle
          gradle --version

      # 9. Build APK
      - name: Build APK
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH

          if [ "$wrapper" == "true" ]; then
            chmod +x ./gradlew
            ./gradlew assembleDebug
          else
            gradle assembleDebug
          fi

      # 10. Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
