name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
  - name: Set up JDK 11
    uses: actions/setup-java@v2
    with:
      distribution: 'temurin'
      java-version: '11'

  - name: Download Android SDK Command Line Tools
    run: |
      sudo apt-get update
      sudo apt-get install unzip wget
      wget https://dl.google.com/android/repository/commandlinetools-linux-9123335_latest.zip
      mkdir -p $HOME/android-sdk/cmdline-tools
      unzip commandlinetools-linux-9123335_latest.zip -d $HOME/android-sdk/cmdline-tools
      mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
      echo "export ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
      echo "export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV

  - name: Install Android SDK packages
    run: |
      source $GITHUB_ENV
      sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-30" "build-tools;30.0.3"

  - name: Accept Licenses
    run: yes | sdkmanager --licenses


      - name: Install Android Tools
        run: |
          yes | sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"

      - name: Build APK
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: bin/*.apk
