name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Android SDK & Tools
        run: |
          echo "Installing Android SDK Command-line Tools"
          sudo mkdir -p /usr/local/android-sdk
          sudo chown $USER:$USER /usr/local/android-sdk
          cd /usr/local/android-sdk

          # Download and extract SDK command-line tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-9477386_latest.zip -d cmdline-tools
          mv cmdline-tools/cmdline-tools cmdline-tools/latest

          # Set environment variables
          export ANDROID_HOME=/usr/local/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH

          # Install essential components
          sdkmanager --sdk_root=$ANDROID_HOME --install \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.2" \
            "ndk;25.2.9519653" \
            "cmake;3.22.1"

          # Accept all licenses
          yes | sdkmanager --licenses

      - name: Verify SDK installation
        run: |
          export ANDROID_HOME=/usr/local/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          sdkmanager --list

      - name: Build the APK
        run: |
          export ANDROID_HOME=/usr/local/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          ./gradlew assembleDebug
          ./gradlew assembleDebug
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      # If your project requires NDK, uncomment this:
      # - name: Install NDK
      #   run: sdkmanager "ndk;25.


      - name: Install Android Tools
        run: |
          yes | sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"

      - name: Build APK
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: bin/*.apk
