name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Setup Java JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle' # Add caching for Gradle dependencies

      # 3. Setup Android SDK
      - name: Setup Android SDK
        # This is a community-created action that handles downloading and configuring the SDK
        uses: android-actions/setup-android@v3
        with:
          # You can specify which packages to install. 
          # platforms;android-34 is a common one to include.
          # You can also add build-tools and other components.
          packages: |
            "build-tools;34.0.0"
            "platforms;android-34"

      # 4. Grant execute permission to the Gradle wrapper
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 5. Build the debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # 6. Upload the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
